In [6]:
import numpy as np

# Q1
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
if array_list.dtype != object:
    print("Data types are different.")
    print("Data type of list_:", type(list_[0]))
    print("Data type of array_list:", array_list.dtype)
        

Data types are different.
Data type of list_: <class 'str'>
Data type of array_list: <U1


In [7]:
# Q2
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))

    

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [8]:
# Q3
array_list = np.array(object=list_, dtype=int)
print("Data types of elements in list_ after converting to int:")
for element in list_:
    print(type(int(element)))

print("Data types of elements in array_list after converting to int:")
for element in array_list:
    print(type(element))


Data types of elements in list_ after converting to int:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
Data types of elements in array_list after converting to int:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [9]:
# Q4
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


In [10]:
# Q5
zeros_array = np.zeros((3, 3))
print("3*3 Matrix containing zeros only:")
print(zeros_array)


3*3 Matrix containing zeros only:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# Q6
identity_matrix = np.eye(5)
print("Identity matrix of shape (5,5):")
print(identity_matrix)

Identity matrix of shape (5,5):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
